"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const native_1 = require("./native");
exports.native = native_1.default;
const es5_1 = require("./es5");
exports.es5 = es5_1.default;
const es6_1 = require("./es6");
exports.es6 = es6_1.default;
const typescript_1 = require("./typescript");
exports.typescript = typescript_1.default;
const migration_1 = require("./migration");
exports.migration = migration_1.default;
